### ISSUE TITLE
docs: spelling error

### ISSUE THREAD

**Issue by adityakode** [predatorprasad/predatorprasad#1]
Hi!
Loved your repo !
Just happened to see an issue in your Readme.md , [here](https://github.com/predatorprasad/predatorprasad#a-passionate-web-developer-and-trurhseeker)
The spelling should be `truthseeker` , but it is misspelt as `Trurhseeker.`

**Comment by predatorprasad** [comment]
Thanks @adityakode for pointing out the typo please submit a PR, would love to see you contribute

**Comment by predatorprasad** [comment]
closed as completed
